# Generated by Django 6.0.1 on 2026-01-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(max_length=250)),
                ('file_types', models.CharField(choices=[('images', 'jpg, png, gif'), ('video', 'mp4'), ('audio', 'mp3, wav'), ('documents', 'pdf, doc, docx'), ('misc', '.xml, log')], default='images', max_length=24)),
            ],
        ),
    ]
